src.utils.exceptions
====================

.. py:module:: src.utils.exceptions

.. autoapi-nested-parse::

   Custom exceptions module.



Exceptions
----------

.. autoapisummary::

   src.utils.exceptions.PluginError
   src.utils.exceptions.ProviderError
   src.utils.exceptions.HostError
   src.utils.exceptions.AuthorizationError
   src.utils.exceptions.SettingsError
   src.utils.exceptions.DataNotFoundError


Module Contents
---------------

.. py:exception:: PluginError(message='', message_type=MessageType.CRITICAL)

   Bases: :py:obj:`Exception`


   Base class for custom exceptions.


   .. py:attribute:: message_type


   .. py:attribute:: message
      :value: ''



.. py:exception:: ProviderError(message=tr('Error to get results from provider.'))

   Bases: :py:obj:`PluginError`


   Custom exception for provider related errors.


.. py:exception:: HostError(message=tr('Error to get results from host.'))

   Bases: :py:obj:`PluginError`


   Custom exception for host related errors.


.. py:exception:: AuthorizationError(message=tr('Error to get results from authorization.'))

   Bases: :py:obj:`PluginError`


   Custom exception for authorization related errors.


.. py:exception:: SettingsError(message=tr('Please check the plugin settings.'))

   Bases: :py:obj:`PluginError`


   Custom exception for settings related errors.


.. py:exception:: DataNotFoundError(message=tr('No data found.'))

   Bases: :py:obj:`PluginError`


   Custom exception for data related errors.


